<?php
session_start();
if($_SESSION['lang']=='es'){
    $lang=array();
    $lang['Checkin']   =   'Llegada';
    $lang['Checkout']   =   'Salida';
    $lang['adults']   =   'Adultos';
    $lang['childrens']   =   'Niños';
    $lang['btn_availability'] = 'Ver disponibilidad';
    $lang['accommodations'] = 'Habitaciones';
    $lang['more_details'] = 'Más detalles';
    $lang['book'] = 'Reservar';
    $lang['reservation_details'] = 'Detalles de reserva';
    $lang['powered']= 'Desarrollado por';
    $lang['theroom']= 'La habitación';
    $lang['room_category']= 'Categoría';
    $lang['price_per_night']= 'Precio por noche';
    $lang['capacity']= 'Capacidad';
    $lang['beddings']= 'Camas';
    $lang['features']= 'Servicios';
    $lang['description']= 'Descripción';
    $lang['air_conditioner']= 'Aire acondicionado';
    $lang['pets_allowed']= 'Mascotas';
    $lang['nights']= 'Noches';
    $lang['room']= 'Habitación';
    $lang['price']= 'Precio';
    $lang['quantity']= 'Cantidad';
    $lang['taxes']= 'Impuestos';
    $lang['guest_info']= 'Quien está reservando?';
    $lang['firstname']= 'Nombre';
    $lang['lastname']= 'Apellido';
    $lang['email']= 'Correo';
    $lang['phone']= 'Teléfono';
    $lang['polices']= 'Política de reservas y cancelaciones';
    $lang['accept_terms']= 'Acepto los términos y condiciones';
    $lang['submit_payment']= 'Efectuar pago';
    $lang['choose_paymet']= 'Escoja su método de pago';
    $lang['credit_card']= 'Tarjeta de crédito';
    $lang['paypal_account']= 'Paypal';
    $lang['charge_today']= 'Monto a pagar';
    echo '<input type="hidden" id="nights_text" value="noches">';
    echo '<input type="hidden" id="night_text" value="noche">';
    echo '<input type="hidden" id="rooms_text" value="habitaciones">';
    echo '<input type="hidden" id="room_text" value="habitación">';
    echo '<input type="hidden" id="and_text" value="y ">';
}else{
    $lang=array();
    $lang['Checkin']   =   'Checkin';
    $lang['Checkout']   =   'Checkout';
    $lang['adults']   =   'Adults';
    $lang['childrens']   =   'Childrens';
    $lang['btn_availability'] = 'Check availability';
    $lang['accommodations'] = 'Rooms';
    $lang['more_details'] = 'More details';
    $lang['book'] = 'Book';
    $lang['reservation_details'] = 'Reservation details';
    $lang['powered']= 'Powered by';
    $lang['theroom']= 'The room';
    $lang['room_category']= 'Room Category';
    $lang['price_per_night']= 'Price per Night';
    $lang['capacity']= 'Capacity';
    $lang['beddings']= 'Beddings';
    $lang['features']= 'Features';
    $lang['description']= 'Description';
    $lang['air_conditioner']= 'Air conditioner';
    $lang['pets_allowed']= 'Mascotas';
    $lang['nights']= 'Nights';
    $lang['room']= 'Room';
    $lang['price']= 'Price';
    $lang['quantity']= 'Quantity';
    $lang['taxes']= 'Taxes';
    $lang['guest_info']= 'Who is reserving?';
    $lang['firstname']= 'First name';
    $lang['lastname']= 'Last name';
    $lang['email']= 'Email';
    $lang['phone']= 'Phone';
    $lang['polices']= 'Reservations and Cancellation Policy';
    $lang['accept_terms']= 'I accept terms and conditions';
    $lang['submit_payment']= 'Submit payment';
    $lang['choose_paymet']= 'Choose your payment method';
    $lang['credit_card']= 'Credit card';
    $lang['paypal_account']= 'Paypal';
    $lang['charge_today']= 'Charge today';
    echo '<input type="hidden" id="nights_text" value="nights">';
    echo '<input type="hidden" id="night_text" value="night">';
    echo '<input type="hidden" id="rooms_text" value="rooms">';
    echo '<input type="hidden" id="room_text" value="room">';
    echo '<input type="hidden" id="and_text" value="and ">';
}
?>